/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tYkZQOSmX9E
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'
import { Judson } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"

export function lessonInfo() {
  return (
    <div className="px-4 py-6 md:px-6 lg:py-12">
      <article className="prose prose-gray mx-auto dark:prose-invert">
        <div className="space-y-2 not-prose">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">Mastering Landscape Photography</h1>
          <p className="text-muted-foreground">Intermediate Level</p>
        </div>
        <p>
          In this lesson, we'll dive into the art of landscape photography and explore the techniques and skills needed
          to capture breathtaking outdoor scenes. Whether you're a beginner or an experienced photographer, you'll learn
          how to compose, expose, and edit your landscape images to bring out the best in your surroundings.
        </p>
        <p>
          We'll cover topics such as understanding natural lighting, using filters to enhance your shots, and leveraging
          composition principles to create visually striking images. By the end of this lesson, you'll have the
          confidence and knowledge to take your landscape photography to the next level.
        </p>
        <Carousel className="w-full max-w-4xl">
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1024}
                height={576}
                alt="Landscape Photo 1"
                className="aspect-video object-cover rounded-md"
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1024}
                height={576}
                alt="Landscape Photo 2"
                className="aspect-video object-cover rounded-md"
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1024}
                height={576}
                alt="Landscape Photo 3"
                className="aspect-video object-cover rounded-md"
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1024}
                height={576}
                alt="Landscape Photo 4"
                className="aspect-video object-cover rounded-md"
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                width={1024}
                height={576}
                alt="Landscape Photo 5"
                className="aspect-video object-cover rounded-md"
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
        <div className="mt-8 space-y-4">
          <h2 className="text-2xl font-bold">Assignment: Capture Your Local Landscape</h2>
          <p>
            For this assignment, we'd like you to venture out and capture the natural beauty of your local landscape.
            This could be a scenic overlook, a serene lake, or a majestic mountain range. Use the techniques you've
            learned in this lesson to compose, expose, and edit your images to showcase the unique character of your
            surroundings.
          </p>
          <p>
            Once you've captured your images, share them with the class and be prepared to discuss your process, the
            challenges you faced, and the lessons you learned. This is a great opportunity to receive feedback and
            continue improving your landscape photography skills.
          </p>
          <Button>Submit Assignment</Button>
        </div>
      </article>
    </div>
  )
}
